---
title: "Untitled"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r }
# 기계학습(50점)
# 1.1 데이터 탐색
# 1.1.1 탐색적 데이터 분석 수행하시오(시각화 포함)
# 1.1.2 이상치 처리하시오
# 1.1.3 앞선 두 단계에서 얻은 향후 분석시 고려사항 작성

# 2.1 클래스 불균형을 처리하시오
# 2.1.1 업 샘플링 과정 설명하고 결과 작성
# 2.2.2 언더 샘플링 과정 설명하고 결과 작성
# 2.2.3 둘 중 선택하고 이유 설명

# 3.1 모델링 하시오
# 3.1.1 최소 3개 이상 알고리즘 제시하고 
# 정확도 측면의 모델 1개와 속도 측면의 모델 1개를 꼭 구현(총 2개 이상)
# 3.1.2 모델 비교하고 결과 설명
# 3.1.3 속도 개선을 위한 차원 축소 설명하고 수행, 예측 성능과 속도 비교하고 결과 작성

# 2. 통계분석(50점)

# 1.1 금속 성분 함유량 변수 1개. (1열 데이터) 
# 제품에 금속 재질 함유량의 분산이 1.3을 넘으면 불량이라고 보고있는데, 
# 제조사별로 차이가 난다고 제보를 받음 분산에 대해 검정을 수행하시오.
# 1.1.1 연구가설과 귀무가설 작성
# 1.1.2 양측 검정 어쩌고
# 1.1.3 검정통계량, 가설 채택


# 2.1 Lot별 불량 제품 수량 데이터. lot 번호와 불량제품수 두 개의 열. 각 lot별 200개에 대한 불량제품 수.
# 2.1.1 p관리도에 따라 관리중심선(center line), 관리 상한선, 하한선 구하시오
# 2.1.2 관리도 시각화 하시오

# 3.1 데이터 없음. 표에 제품 1,2를 만드는데 사용되는 재료 a b c 컬럼 있고 
# 재료에 따라 최종 만들어지는 제품 두 개에 대한 수량 있음. 
# 최하단 행에는 수익이 있음. 
# 제품 수량을 최대로 뽑으면서 수익이 최적이 되도록 하라고 함.(10점)

# 4.1 데이터 없음. 상품 a와 b가 있을 때 다음과 같은 구매 패턴이 있다고 함. 
# aa bb bbbb aa aaa bb bbb aa bb a b 정확히 기억 안나지만 대충 비슷함. 
# 4.1.1 구매하는 패턴으로 봐서 두 상품이 연관이 있는지 가설 세우고 검정하시오
# 4.1.2 연구가설 귀무가설 세우시오
# 4.1.3 가설 채택하시오


############################ 문제 풀이 ##########################
# 1.1 데이터 탐색
# 1.1.1 탐색적 데이터 분석 수행하시오(시각화 포함)
# 1.1.2 이상치 처리하시오
# 1.1.3 앞선 두 단계에서 얻은 향후 분석시 고려사항 작성

library(tidyverse)
library(magrittr)
library(caret)
library(recipes)
library(funModeling)
library(knitr)

rm(list=ls())
setwd("D:/#000.자격증공부/#003. ADP실기/각종주제별코드/R과외/study/ADP기출/")

read.csv("data.csv") -> data 
data %>%  names()
# [1] "Pregnancies"              "Glucose"                  "BloodPressure"           
# [4] "SkinThickness"            "Insulin"                  "BMI"                     
# [7] "DiabetesPedigreeFunction" "Age"                      "Outcome"

data  %>%  glimpse()
data$Outcome %<>%  as.factor()


# 목적변수 탐색 
data %>%  ggplot() + geom_bar() + 
  aes(x=Outcome, fill = Outcome)
data$Outcome %>% table() %>%  prop.table() %>%  round(3) 

# 탐색 결과 
# 분류 모델이다. 
# 0의 비율이 1에 비해 2배 많다. (Imbalanced data 이다.)


```
